# Generated by Django 3.0.4 on 2020-03-29 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('deck', models.CharField(max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='rooms_players', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='rooms_viewers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
