# Generated by Django 3.0.4 on 2020-03-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200329_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='starting_chips',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
