# Generated by Django 3.0.4 on 2020-03-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deck',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
