# Generated by Django 3.0.4 on 2020-04-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_starting_chips'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('INITIALIZED', 'Initialized'), ('USER_CARDS_DEALT', 'User Cards Dealt'), ('FLOP_DEALT', 'Flop Dealt'), ('TURN_DEALT', 'Turn Dealt'), ('RIVER_DEALT', 'River Dealt')], default='NOT_STARTED', max_length=40),
        ),
    ]
