# Generated by Django 3.0.4 on 2020-03-30 04:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_starting_chips'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(api.models.GameState['NOT_STARTED'], 0), (api.models.GameState['INITIALIZED'], 1), (api.models.GameState['USER_CARDS_DEALT'], 2), (api.models.GameState['FLOP_DEALT'], 3), (api.models.GameState['TURN_DEALT'], 4), (api.models.GameState['RIVER_DEALT'], 5)], default=0),
        ),
    ]
