# Generated by Django 3.0.4 on 2020-03-30 05:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[(api.models.GameState['NOT_STARTED'], 'NOT_STARTED'), (api.models.GameState['INITIALIZED'], 'INITIALIZED'), (api.models.GameState['USER_CARDS_DEALT'], 'USER_CARDS_DEALT'), (api.models.GameState['FLOP_DEALT'], 'FLOP_DEALT'), (api.models.GameState['TURN_DEALT'], 'TURN_DEALT'), (api.models.GameState['RIVER_DEALT'], 'RIVER_DEALT')], default=api.models.GameState['NOT_STARTED'], max_length=40),
        ),
    ]
