# Generated by Django 3.0.4 on 2020-03-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='deck',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
